version: 2.1

orbs:
  circleci-cli: circleci/circleci-cli@0.1.8
  orbs: circleci/orb-tools@10.0.0
  general: shapertools/general@0.1.4

workflows:
  main:
    jobs:
      - general/install-dependencies-npm
      - general/lint-commit:
          requires:
            - general/install-dependencies-npm
      - general/lint-json:
          requires:
            - general/install-dependencies-npm
      - general/lint-yaml:
          requires:
            - general/install-dependencies-npm
      - general/lint-circleci-orb:
          requires:
            - general/install-dependencies-npm
      - general/publish-circleci-dev:
          context: Orb Publishing
          orb-ref: shapertools/general
          token-variable: ORB_PUBLISHING_TOKEN
          requires:
            - general/lint-commit
            - general/lint-json
            - general/lint-yaml
            - general/lint-circleci-orb
          filters:
            branches:
              ignore: master
      - general/create-release-pr:
          context: Release Bot
          git-ssh-fingerprint: 5c:6b:55:e8:b5:43:d5:0c:79:09:7a:a6:29:6b:39:84
          git-user-email: jenkins-deploy@users.noreply.github.com
          git-user-name: "Release Bot"
          github-access-token: $RELEASE_BOT_GITHUB_TOKEN
          requires:
            - general/lint-commit
            - general/lint-json
            - general/lint-yaml
            - general/lint-circleci-orb
          filters:
            branches:
              only: master
      - general/tag-and-publish-circleci:
          context: Orb Publishing
          git-ssh-fingerprint: 5c:6b:55:e8:b5:43:d5:0c:79:09:7a:a6:29:6b:39:84
          git-user-email: jenkins-deploy@users.noreply.github.com
          git-user-name: "Release Bot"
          orb-ref: shapertools/general
          token-variable: ORB_PUBLISHING_TOKEN
          requires:
            - general/lint-commit
            - general/lint-json
            - general/lint-yaml
            - general/lint-circleci-orb
          filters:
            branches:
              only: master
      - general/create-github-release:
          context: Release Bot
          github-access-token: $RELEASE_BOT_GITHUB_TOKEN
          requires:
            - general/tag-and-publish-circleci
          filters:
            branches:
              only: master
